inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/MethodName:
  Enabled: false

Style/LambdaCall:
  Enabled: false

Style/StabbyLambdaParentheses:
  Enabled: false

Style/NestedParenthesizedCalls:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Metrics/LineLength:
  Max: 110

Style/FileName:
  Exclude:
    - 'lib/dry-monads.rb'

Lint/Debugger:
  Exclude:
    - 'bin/console'

Lint/HandleExceptions:
  Exclude:
    - 'spec/spec_helper.rb'
