language: ruby
dist: trusty
sudo: false
cache: bundler
bundler_args: --without benchmarks docs
script:
  - bundle exec rake spec
before_install:
  - gem update --system
after_success:
  - '[ -d coverage ] && bundle exec codeclimate-test-reporter'
rvm:
  - 2.2.10
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6
  - ruby-head
  - jruby-9.2.0.0
env:
  global:
    - JRUBY_OPTS='--dev -J-Xmx1024M'
    - COVERAGE=true
matrix:
  allow_failures:
    - rvm: ruby-head

notifications:
  email:
    recipients:
      - fg@flashgordon.ru
    on_success: change
    on_failure: always
    on_start: false     # default: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/19098b4253a72c9796db
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
