language: ruby
dist: trusty
sudo: false
cache: bundler
bundler_args: --without benchmarks
script:
  - bundle exec rake spec
after_success:
  - '[ -d coverage ] && bundle exec codeclimate-test-reporter'
rvm:
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - 2.4.1
  - jruby-9.1.8.0
  - ruby-head
env:
  global:
    - JRUBY_OPTS='--dev -J-Xmx1024M'
    - COVERAGE=true
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-3
  include:
    - rvm: jruby-head
      before_install: gem update bundler
    - rvm: rbx-3
      before_install: gem update bundler

notifications:
  email:
    recipients:
      - fg@flashgordon.ru
    on_success: change
    on_failure: always
    on_start: false     # default: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/19098b4253a72c9796db
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
